version: '3'
services:
  init:
    image: busybox
    volumes:
      - ./local-data/philomena:/system
    command: /bin/chown -v 200:200 /system
    restart: "no"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    environment:
      - MIX_ENV=prod
      - PGPASSWORD=postgres
      - ELASTICSEARCH_HOST="http://elasticsearch:9200"
      - SECRET_KEY_BASE=ZosAlRnAL0P1e7PpdLTEwLw80TQzcN4rRV5cwFuBB3Pg7AmrDKr3Pu2QWfgaZ1hK
    tty: true
    depends_on:
      - postgres
      - elasticsearch
      - redis
    volumes:
      - ./local-data/philomena:/srv/philomena/priv/static/system
    # for debugging into the container when container-start fails, umcomment the following line:
    #entrypoint: ["sh", "-c", "sleep 2073600"]

  gdpr-cron:
    build:
      context: ./docker/gdpr
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGDATABASE: philomena_db
      PGUSER: postgres
      PGPASSWORD: postgres

  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./local-data/postgres:/var/lib/postgresql/data
    logging:
      driver: "none"

  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
      - ./local-data/elastic:/var/lib/elasticsearch
    logging:
      driver: "none"
    environment:
      - discovery.type=single-node
    ulimits:
      nofile:
          soft: 65536
          hard: 65536

  redis:
    image: redis:5.0.9
    logging:
      driver: "none"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    depends_on:
      - app
    extra_hosts:
      - kube-dns.kube-system.svc.cluster.local:127.0.0.11
    environment:
      - APP_HOST=app
    tmpfs:
      - /tmp
    ports:
      - '8080:8080'
    volumes:
      - ./local-data/philomena:/system
      - ./local-data/philomena:/srv/philomena/priv/static/system
